version : '3.8'

services:
   db:
      image: postgres:latest
      environment:
        POSTGRES_USER: survey_dev
        POSTGRES_PASSWORD: surveys_2026
        POSTGRES_DB: surveydb_dev
      ports:
        - "5432:5432"
      volumes:
        - db_data:/var/lib/postgresql/data/
    

volumes:
   db_data: