# Generated by Django 4.2.5 on 2023-09-07 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("topic", models.CharField(default="hola", max_length=50)),
                ("question", models.CharField(max_length=200)),
                ("creator", models.CharField(max_length=100)),
                ("submissions", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                (
                    "password",
                    models.CharField(
                        default="", max_length=128, verbose_name="password"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="",
                        error_messages={
                            "required": "Please provide your email address.",
                            "unique": "An account with this email exist.",
                        },
                        max_length=254,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Results",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selectedchoice", models.CharField(max_length=100)),
                ("votes", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveyapp.survey",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Choices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_1", models.CharField(max_length=100)),
                ("choice_2", models.CharField(max_length=100)),
                ("choice_3", models.CharField(max_length=100)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveyapp.survey",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Uservotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("answer", models.CharField(max_length=100)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveyapp.survey",
                    ),
                ),
            ],
            options={"unique_together": {("username", "answer")},},
        ),
    ]
