# Generated by Django 4.1 on 2023-07-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveyapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choices", old_name="menu", new_name="question",
        ),
        migrations.AlterField(
            model_name="survey",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
