# Generated by Django 4.2.5 on 2023-09-07 10:19

from django.db import migrations, models
import surveyapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("surveyapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uservotes",
            name="answer",
            field=models.CharField(
                max_length=100, verbose_name=surveyapp.models.Choices
            ),
        ),
    ]
