# Generated by Django 4.2.5 on 2023-09-07 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("surveyapp", "0002_alter_uservotes_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uservotes",
            name="answer",
            field=models.ForeignKey(
                max_length=100,
                on_delete=django.db.models.deletion.CASCADE,
                to="surveyapp.choices",
            ),
        ),
    ]
