# Generated by Django 4.1 on 2023-07-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveyapp", "0002_rename_menu_choices_question_alter_survey_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="topic",
            field=models.CharField(default="hola", max_length=50),
        ),
    ]
