# Generated by Django 4.2.5 on 2023-09-07 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveyapp", "0005_alter_uservotes_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uservotes", old_name="question", new_name="question_name",
        ),
        migrations.AlterUniqueTogether(
            name="uservotes", unique_together={("question_name", "username", "answer")},
        ),
    ]
