# Generated by Django 4.2.5 on 2023-09-07 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("surveyapp", "0009_alter_uservotes_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uservotes",
            name="question_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="surveyapp.survey"
            ),
        ),
    ]
