# Generated by Django 4.2.5 on 2023-09-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0013_alter_survey_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Finished', 'Finished')], max_length=15),
        ),
    ]
